language: ruby
rvm:
  - 2.0.0
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
before_script:
  - psql -c 'create database nastachku_test' -U postgres
  - cp config/database.yml.sample config/database.yml
  - cp config/credentials.yml.sample config/credentials.yml
  - mkdir tmp && mkdir tmp/cache
services:
  - redis-server
